FROM golang:1.21 AS builder

WORKDIR /app
COPY go.mod .
COPY main.go .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o http-echo-server .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/http-echo-server .
EXPOSE 8080 9090
ENV PORT1=8080
ENV PORT2=9090
CMD ["./http-echo-server"]