FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod .
COPY main.go .
RUN CGO_ENABLED=0 go build -ldflags "-extldflags '-static'" -o http-echo-server

FROM gcr.io/distroless/static
COPY --from=builder /app/http-echo-server /
EXPOSE 8080 9090
CMD ["/http-echo-server"]